### ISSUE TITLE
suggestion: document use as systemd journalctl pager

### ISSUE THREAD

**Issue by jonassmedegaard** [bensadeh/tailspin#28] opened 2023-07-23 18:04 UTC
You might want to add a note to documentation that this is how to make tailspin your pager for systemd journalctl:
```
SYSTEMD_PAGERSECURE=true PAGER=/usr/bin/tailspin journalctl
```

...but you might wanna first implement #27 since currently your pager *isn't* secure.

Also, the above does not actually work - adding option `-f` or `-e` works but calling bare journalctl just hangs with nothing output to screen. :-(

**Comment by bensadeh** [comment] 2023-07-26 09:58
Have you had a chance to test the new `--tail-command` flag? Does this affect the current setup?

**Comment by jonassmedegaard** [comment] 2023-07-26 14:51
No, haven't taken time to look into that yet.

**Comment by bensadeh** [comment] 2023-07-31 15:45
I have reworked how tailspin handles piping in `1.3.0`. From here on, it will output everything to stdout if we try to pipe anything to it from stdin. I believe this behavior will make it easier to combine tailspin in other scripts. It also makes it easier to pipe to. I still have the now renamed `--follow-command` flag for those who want to remain in the less pager while still "following" the stdout output of a given command.

Will these changes affect how tailspin can be used with `systemd` and `journalctl`?

**Comment by bensadeh** [comment] 2023-08-05 06:40
I believe that with the changes from `1.3.0`, these commands would work as expected:

```console
journalctl -f | spin
journalctl -ef | spin
```

The commands above would be similar to `tail -f`, meaning it will just output to `stdout` until it is interrupted.

If you wanted to stay inside `less` while maintaining the ability to drop in and out of follow mode, then we can still use the `--follow-command` flag:

```console
spin --follow-command 'journalctl -f'
```

However I am not on Debian, so I cannot confirm this. Let me know if it is working as intended, then we can update the readme.

**Comment by bensadeh** [comment] 2023-10-06 15:41
Closing this as the readme has been updated.

**Closed by bensadeh** 2023-10-06 15:41 UTC
