### ISSUE TITLE
highlighting for log levels

### ISSUE THREAD

**Issue by sam-huang1223** [bensadeh/tailspin#73] opened 2023-11-06 03:24 UTC
would appreciate easy differentiation between INFO and DEBUG and etc.

**Comment by bensadeh** [comment] 2023-11-07 07:08
In the upcoming release of `2.1.0`, I will add support for disabling the builtin severity keywords, then you re-create them with the styling you prefer.

Closing as duplicate of https://github.com/bensadeh/tailspin/issues/60 for now.

**Closed by bensadeh** 2023-11-07 07:08 UTC
