### ISSUE TITLE
Where is default config file location?

### ISSUE THREAD

**Issue by frakman1** [bensadeh/tailspin#64] opened 2023-11-03 14:27 UTC
I want to add new custom keywords but I want them to match the colors used by default for INFO, WARN, ERROR etc
I have created my own `~/.config/tailspin/config.toml` file but don't want to guess what those color values are.

So what does tailspin use to decide what those colors should be by default? Is it embedded in the code or is there some config file I can look at?

**Comment by frakman1** [comment] 2023-11-03 14:35
I found in the source code (`src/theme/defaults.rs`) where some of this is defined but I don't know how to replicate 'faint' for something like 'TRACE'

<img width="293" alt="image" src="https://github.com/bensadeh/tailspin/assets/5826484/e44c64b6-5c48-47c8-911f-4591f175b511">

**Comment by frakman1** [comment] 2023-11-03 14:49
Also, how do I get this gray color? (`HISTORY_SHARED_BUFFER_NAME`) It shows up when I am viewing a log file in `spin`:

<img width="1078" alt="image" src="https://github.com/bensadeh/tailspin/assets/5826484/6938d009-7925-4c26-a805-497fd4ef681b">

**Comment by bensadeh** [comment] 2023-11-05 07:29
Hi

**Comment by bensadeh** [comment] 2023-11-05 07:29
Hi

**Comment by bensadeh** [comment] 2023-11-05 07:34
Hi @frakman1,

Thanks for opening the issue. 

You're right, they are hard coded at the moment. Disabling severity keywords is coming in `2.1.0`, and that way you can define your own or override them as you want.

The gray color comes from the fact that `tailspin` identifies that part as a Key Value type log, so it will dim the key by default. You can disable this now from the toml if this is not wanted.

I'll close this as a duplicate of #60, but the option to disable the hard coded severity words will come in `2.1.0`.

**Closed by bensadeh** 2023-11-05 07:34 UTC
